#ifndef __CONFIGC_ERROR
#define __CONFIGC_ERROR

#define ERR_FILE_NOT_EXIST 1;
#define ERR_UNABLE_OPEN_FILE 2;
#define ERR_UNABLE_READ_FILE 3;
#define ERR_UNABLE_WRITE_FILE 4;
#define ERR_UNABLE_REMOVE_FILE 6;
#define ERR_UNABLE_TRUNCATE_FILE 8;
#define ERR_MAX_IO_SIZE 7;
#define ERR_FILE_TOO_BIG 8;
#define ERR_IO_MAX_RETRY_REACHED 9;

#endif
